version: "3.8"

services:
    nginx:
        image: nginx
        container_name: nginx
        build:
            dockerfile: Dockerfile
            context: ./requirements/nginx/
        hostname: nginx
        networks:
            - inception
        ports:
            - 443:443
        restart: always
        volumes:
            - wordpress-data:/var/www/html/
        depends_on:
            - "wordpress"

    mariadb:
        image: mariadb
        container_name: mariadb
        build:
            dockerfile: Dockerfile
            context: ./requirements/mariadb/
        hostname: mariadb
        env_file:
            - .env
        networks:
            - inception
        restart: on-failure
        volumes:
            - mariadb-data:/var/lib/mysql/

    wordpress:
        image: wordpress
        container_name: wordpress
        build:
            dockerfile: Dockerfile
            context: ./requirements/wordpress/
        hostname: wordpress
        env_file:
            - .env
        networks:
            - inception
        restart: on-failure
        volumes:
            - wordpress-data:/var/www/html/
        depends_on:
            - "mariadb"

networks:
    inception:
        name: inception
        driver: bridge

volumes:
  mariadb-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/home/${USER}/data/database"
  wordpress-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/home/${USER}/data/website"
